[package]
name = "workstation"
version = "0.6.0"
description = "A Tauri app to manage and optimize developer daily work"
authors = ["L1MeN9Yu"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "workstation_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "rustls-tls"] }
futures-util = "0.3"
bytes = "1"
log = "0.4"
log4rs = { version = "1", default-features = false, features = ["file_appender", "console_appender", "pattern_encoder", "chrono"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
sha2 = "0.10"
base64 = "0.22"
fontdb = "0.24.0"
image = "0.25"
tauri-plugin-dialog = "2"
filetime = "0.2.29"
rusqlite = { version = "0.31", features = ["bundled"] }

[dev-dependencies]

